# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0
    ports:
      - 4444:4444

#  real_device:
#    image: appium/appium
#    depends_on:
#      - selenium_hub
#    network_mode: "service:selenium_hub"
#    privileged: true
#    volumes:
#      #- /dev/bus/usb:/dev/bus/usb
#      #- ~/.android:/root/.android
#      - ./example/sample_apk:/root/tmp
#    environment:
#      - CONNECT_TO_GRID=false
#      - SELENIUM_HOST=selenium_hub
#      - RELAXED_SECURITY=true

  nexus_7.1.1:
    image: butomo1989/docker-android-x86-8.1
    privileged: true
    scale: 1
    depends_on:
      - selenium_hub
      #- real_device
    ports:
      - 6091:6080
      - 4723:4723
      - 5554:5554
      - 5555:5555
    volumes:
      - ./example/sample_apk:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=False
      - AUTO_RECORD=true
  
  samsung_galaxy:
    image: butomo1989/docker-android-x86-8.1
    privileged: true
    scale: 1
    depends_on:
      - selenium_hub
      #- real_device
    ports:
      - 6090:6080
      - 4724:4723
    volumes:
      - ./example/sample_apk:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=False
      - AUTO_RECORD=true
      